import os
import json
import argparse
from collections import defaultdict
import numpy as np
import matplotlib.pyplot as plt

CLASS_LABELS_20 = (
    "wall", "floor", "cabinet", "bed", "chair", "sofa", "table",
    "door", "window", "bookshelf", "picture", "counter", "desk",
    "curtain", "refrigerator", "shower curtain", "toilet", "sink",
    "bathtub", "otherfurniture",
)

def main():
    parser = argparse.ArgumentParser(description="Generate stacked bar chart of furniture counts per scene type.")
    parser.add_argument(
        "--json_path", type=str,
        default="",
        help="Path to per_scene_classes.json generated by the original furniture_histogram.py script"
    )
    parser.add_argument(
        "--data_root", type=str,
        default="",
        help="Path to scannet_all_processed dataset to read scene_type.txt files"
    )
    parser.add_argument(
        "--output_dir", type=str,
        default="",
        help="Output directory to save the resulting image"
    )
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    if not os.path.exists(args.json_path):
        print(f"Error: Could not find JSON file at {args.json_path}")
        return

    with open(args.json_path, 'r') as f:
        per_scene_data = json.load(f)

    # type_to_counts[scene_type][class_idx] = count of scenes of this type containing this class
    type_to_counts = defaultdict(lambda: defaultdict(int))

    print("Processing scene data...")
    for item in per_scene_data:
        scene = item["scene"]
        inf_classes = item.get("inf_classes", [])
        
        # Read scene type
        st_path = os.path.join(args.data_root, scene, "scene_type.txt")
        if os.path.exists(st_path):
            with open(st_path) as f:
                scene_type = f.read().strip()
        else:
            scene_type = "Unknown"
            
        # Tally the occurrences of each class for this scene type
        for c in inf_classes:
            if c < 20: 
                type_to_counts[scene_type][c] += 1

    # Sort scene types by the total volume of elements present to make the chart look nice
    unique_scene_types = sorted(type_to_counts.keys(), key=lambda t: sum(type_to_counts[t].values()), reverse=True)
    
    print(f"Found {len(unique_scene_types)} unique scene types.")

    x_labels = unique_scene_types
    x_pos = np.arange(len(x_labels))
    
    # Store counts in a 2D numpy array [class_idx, scene_type_idx]
    counts_matrix = np.zeros((len(CLASS_LABELS_20), len(x_labels)))
    for t_idx, st in enumerate(x_labels):
        for c_idx in range(len(CLASS_LABELS_20)):
            counts_matrix[c_idx, t_idx] = type_to_counts[st][c_idx]

    print("Generating stacked bar chart...")
    
    # Initialize figure
    fig, ax = plt.subplots(figsize=(18, 9))
    fig.patch.set_facecolor("white")
    ax.set_facecolor("#f9f9f9")

    bottoms = np.zeros(len(x_labels))
    
    # Get a 20-color colormap for the 20 classes
    cmap = plt.get_cmap("tab20")
    colors = cmap(np.linspace(0, 1, 20))

    # Stack the bars
    for c_idx in range(len(CLASS_LABELS_20)):
        row = counts_matrix[c_idx]
        ax.bar(
            x_pos, row, bottom=bottoms, 
            label=CLASS_LABELS_20[c_idx], 
            color=colors[c_idx], 
            edgecolor='white', 
            linewidth=0.5,
            width=0.75
        )
        bottoms += row

    # Aesthetics
    ax.set_xticks(x_pos)
    ax.set_xticklabels(x_labels, rotation=45, ha='right', fontsize=13, color="#222222")
    
    ax.set_ylabel("Total Furniture Class Detections (Scene Summation)", fontsize=14, color="#111111", labelpad=15)
    ax.set_title("Distribution of Furniture Detectons across Scene Types\n(Entire Dataset | Sonata Inference)", 
                 fontsize=18, pad=20, weight='bold', color="#111111")
                 
    ax.tick_params(axis='y', labelsize=12, colors="#222222")
    ax.grid(axis='y', linestyle='--', alpha=0.5, color="#bbbbbb", zorder=0)

    # Legend
    ax.legend(
        title="Furniture Classes (ScanNet-20)", 
        title_fontsize=13,
        fontsize=11,
        bbox_to_anchor=(1.02, 1), 
        loc='upper left', 
        frameon=True,
        facecolor="white",
        edgecolor="#dddddd"
    )

    # Strip top and right borders
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#aaaaaa')
    ax.spines['bottom'].set_color('#aaaaaa')

    plt.tight_layout()
    
    out_path = os.path.join(args.output_dir, "scene_type_furniture_distribution.png")
    plt.savefig(out_path, dpi=200, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()
    
    print(f"Successfully generated and saved histogram to -> {out_path}")

if __name__ == "__main__":
    main()
